spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emp_test?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-calss-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto = update